# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ""
masthead_title: "Javier Fuentes Alonso"
email: javierfuentesalonso@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Javier Fuentes Alonso personal website. 
twitter_username: JavierFnts
github_username: JaviFuentes94
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Javier Fuentes Alonso"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Building ML systems for the real world. I teach computers to design at uizard.io"
  location: "Copenhagen, Denmark"
  links:
    - label: " Research Engineer @ Uizard"
      icon: "fas fa-briefcase"
      url: "https://uizard.io/"
    - label: " Subscribe"
      icon: "fas fa-envelope-open-text"
      url: "https://tinyletter.com/JavierFuentes"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JavierFnts"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/javier-fuentes-alonso/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JaviFuentes94"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JavierFnts"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/javier-fuentes-alonso/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JaviFuentes94"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google"
  google:
    tracking_id: "UA-186160150-1"
    anonymize_ip: false # default

twitter:
  username: "JavierFnts"
